### ISSUE TITLE
Node 20 compatibility

### ISSUE THREAD

**Issue by fgeierst** [testing-accessibility/workshop-manual-a11y-testing#3]
I could not install the project as is, probably because my machine's node version is v20.5.1. 

Updating the NPM dependencies by running `npx taze major -w && npm install` resolved the issue for me.

**Comment by wencyen** [comment]
Thanks for pointing out the node version. For me, I just needed to switch my node version using `nodenv`

**Comment by marcysutton** [comment]
Thanks for the issue. The packages needed to be upgraded, which I just pushed to the main branch. I'm going to close this as resolved but if it persists or you run into problems, let me know!
